### ISSUE TITLE
New version tag for bower.

### ISSUE THREAD

**Issue by dlazerka** [loicfrering/backbone.handlebars#9]
Bower still serves `v0.2.0` with commit 24e5a2f8f88957f5d26cc66bd8e50a8dcf40fa76 (where git tag is pointing to), and so doesn't have fixes since that commit.
New version (like `v0.2.1`) is needed.
Alternatively can be done by force-push the `v0.2.0` tag to the latest commit, but that might create problems for users.

**Comment by loicfrering** [comment]
Hi @dlazerka, thanks for your interest for Backbone Handlebars! I just pushed v0.2.1 in 17c07104199e7275eb68a0089498f7e16606fde0.
